json-everything/json-everything

- JsonSchema.Tests/SerializationTests.cs
- JsonSchema/ReadOnlyKeyword.cs
Wasn't quite sure how you'd test this (I wasn't able to load the `Suite` tests - in VS) so I added just one of the most basic ones I could find. Please let me know how to improve if required.
> fix error condition in ReadOnlyKeywordJsonConverter

- Json.More/Json.More.xml
- JsonSchema.Tests/GithubTests.cs
- JsonSchema/JsonSchema.csproj
- JsonSchema/RefKeyword.cs
- docs_source/release-notes/json-schema.md
> undo a change made to refkeyword

- Json.More.Tests/Json.More.Tests.csproj
- Json.More.Tests/UnitTest1.cs
- Json.More/EnumStringConverter.cs
- JsonSchema.Generation.Tests/SchemaGenerationTests.cs
- JsonSchema.Generation/Generators/ObjectSchemaGenerator.cs
- json-everything.sln
There is a race condition in `EnumStringConverter` that was found when running unit tests in parallel. Multiple tests serializing distinct `JsonSchema` objects at the same time can cause this race condition to be hit.
**Example stack trace:**
```
Error Message:
System.NullReferenceException : Object reference not set to an instance of an object.
Stack Trace:
at Json.More.EnumStringConverter`1.Write(Utf8JsonWriter writer, T value, JsonSerializerOptions options)
at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
at System.Text.Json.Serialization.JsonConverter`1.WriteCore(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
at …
```
> Fix race condition in EnumStringConverter, fix name that is added to required list in ObjectSchemaGenerator

- JsonSchema.Generation.Tests/AttributeHandlerTests.cs
- JsonSchema.Generation.Tests/PropertyOrderTests.cs
- JsonSchema.Generation/AttributeHandler.cs
- JsonSchema.Generation/Generators/ObjectSchemaGenerator.cs
- JsonSchema.Generation/JsonSchema.Generation.csproj
- JsonSchema.Generation/JsonSchema.Net.Generation.xml
- JsonSchema.Generation/PropertyOrder.cs
- JsonSchema.Generation/SchemaGeneratorConfiguration.cs
- docs_source/release-notes/json-schema-generation.md
- docs_source/usage/schema-generation.md
Depends on #110
Fixes #109
Fixes #112
> SchemaGen v1.4.0

- Json.More/JsonElementExtensions.cs
- JsonLogic/Rule.cs
- JsonLogic/RuleExtensions.cs
- JsonLogic/Rules/ReduceRule.cs
- JsonPatch/EditableJsonElement.cs
- JsonPath/PropertyNameIndex.cs
- JsonPath/SpanExtensions.cs
- JsonSchema/ConstKeyword.cs
- JsonSchema/DefaultKeyword.cs
- JsonSchema/EnumKeyword.cs
- JsonSchema/ExamplesKeyword.cs
- JsonSchema/JsonSchema.cs
- JsonSchema/RequiredKeyword.cs
- JsonSchema/SchemaKeyword.cs
- JsonSchema/SchemaKeywordRegistry.cs
JsonDocument rents from ArrayPool and must be disposed to prevent memory leaks.
> Fix memory leaks.

- JsonSchema.Generation.Tests/PropertyOrderTests.cs
- JsonSchema.Generation/Generators/ObjectSchemaGenerator.cs
- JsonSchema.Generation/JsonSchema.Net.Generation.xml
- JsonSchema.Generation/MemberInfoMetadataComparer.cs
- JsonSchema.Generation/SchemaGeneratorContext.cs
See [this comment](https://github.com/gregsdennis/json-everything/issues/112#issuecomment-845935019) in #112 for more details.
This PR extends the "as declared" property ordering to ensure that members are ordered from least-derived type to most-derived type, and then in declaration order in each individual type.
Consider the following types:
```csharp
public class BaseClass {
public int First { get; set; }
public int Second { get; set; }
}
public class DerivedClass : BaseClass {
public int Third { get; set; }
public int Fourth { get; set; }
}
```
When generating a schema for `DerivedClass` using `PropertyOrder.AsDeclared`, the order of properties in the schema is currently:
- `Third`
- `Fourth`
- `First`
- `Second`
This PR ensures that the properties from `BaseClass` are listed before …
> Order properties by type and then declaration order

- JsonSchema/JsonSchema.cs
- JsonSchema/SchemaRegistry.cs
- JsonSchema/ValidationOptions.cs
While using your library in an asp.net core project I hit some unexpected failures. The only reproducer I managed to find out required concurrent validations, which pointed in the direction of some issue in the thread-safety of the library.
I am quite confident that the issue stems from
https://github.com/gregsdennis/json-everything/blob/f52854937a06afa87794345cb8e66bb1d2d45ee8/JsonSchema/SchemaRegistry.cs#L66-L73
as this makes it possible for two threads A & B to perform the following:
- A proceeds up to line 72, yields;
- B finds `Global._options != null` at line 66, `return`s and performs the validation (without the MetaSchemas registrations)
- A finally continues with line 73 and beyond
A fix for this race condition could be implemented by moving line `71` to the very bottom of the …
> Make initialization of the static classes thread-safe

- JsonPatch.Tests/PatchExtensionTests.cs
- JsonPatch/PatchExtensions.cs
In arrays there was a bug because incorrect usage of JsonPointer.Parse.
Paths were like /0test instead of /0/test
> fix bug in create patch when property type (ValueKind) was changed

- .github/workflows/dotnet-core.yml
- JsonSchema.Tests/UnrecognizedKeywordTests.cs
- JsonSchema/JsonSchema.cs
- JsonSchema/JsonSchema.csproj
- JsonSchema/JsonSchemaBuilderExtensions.cs
- JsonSchema/KeywordExtensions.cs
- JsonSchema/UnrecognizedKeyword.cs
- json-everything.net/wwwroot/md/release-notes/json-schema.md
Special request from @relequestual.  This has also be rolling around in my head for a few weeks anyway.
> added a keyword impl for unrecognized keywords instead of otherdata

- JsonSchema.Generation.Tests/ClientTests.cs
- JsonSchema.Generation/GeneratorRegistry.cs
- JsonSchema.Generation/Generators/JsonArraySchemaGenerator.cs
- JsonSchema.Generation/Generators/JsonObjectSchemaGenerator.cs
- JsonSchema.Generation/Generators/JsonValueSchemaGenerator.cs
- JsonSchema.Generation/JsonSchema.Generation.csproj
- JsonSchema.Generation/SchemaGenerationContextBase.cs
- JsonSchema.Generation/SchemaGenerationContextOptimizer.cs
- json-everything.net/wwwroot/md/release-notes/json-schema-generation.md
- json-everything.net/wwwroot/md/schema-generation.md
> Issue275 jsonobject causes argumentexception

- JsonSchema.Generation/Generators/ObjectSchemaGenerator.cs
I'm typically adding
`[JsonIgnore(Condition = JsonIgnoreCondition.Never)]`
to my classes, to ensure that serialized json has the format I want,
even if someone changes the global `JsonIgnoreCondition`.
This means that the existance of `JsonIgnore` is not enough, but you
need to check that `Condition == JsonIgnoreCondition.Always`.
The Docs for `[JsonIgnore]` states that `Always` is the default condition
and the other conditions does not indicate that the property should be
ignored from schema.
https://docs.microsoft.com/en-us/dotnet/api/system.text.json.serialization.jsonignoreattribute.condition?view=net-6.0
> Check Condition on System.Text.Json.JsonIgnoreAttribute

- JsonSchema.Generation.Tests/SchemaGenerationTests.cs
The discussion in https://github.com/gregsdennis/json-everything/pull/296 seems to indicate that there should be some tests to ensure that the ignore attributes are read in correct order.
* `[JsonExclude]` will override for schema generation, regardless of other properties present.
* `[JsonIgnore]` will only be used to ignore properties when the condition is `Condition= JsonIgnoreCondition.Always`, `[JsonIgnore(Condition= JsonIgnoreCondition.Never)]`, will not cause the property to be removed.
> Add test cases for ignoring properties

- JsonPatch.Tests/PatchExtensionTests.cs
- JsonPatch/PatchExtensions.cs
Hello there!
I've noticed that in the `Apply<T1, T2>()` `JsonPatch` extension method the given `JsonSerializerOptions` argument is not passed forward to the `JsonSerializer.SerializeToNode()` function. This caused some issues that I've reproduced in a unit test.
Thanks!
> Add missing options argument to serializer during apply

- JsonLogic.Tests/GithubTests.cs
- JsonLogic/JsonLogic.csproj
- JsonLogic/JsonNodeExtensions.cs
- json-everything.net/wwwroot/md/release-notes/json-logic.md
> Logic v3.1.2

- JsonSchema.Data.Tests/Tests.cs
- JsonSchema.Data/DataKeyword.cs
- JsonSchema.Data/IDataResourceIdentifier.cs
- JsonSchema.Data/JsonPointerIdentifier.cs
- JsonSchema.Data/JsonSchema.Data.csproj
- JsonSchema.Data/JsonSchemaBuilderExtensions.cs
- JsonSchema.Data/MetaSchemas.cs
- JsonSchema.Data/RefResolutionException.cs
- JsonSchema.Data/RelativeJsonPointerIdentifier.cs
- JsonSchema.Data/UriIdentifier.cs
- JsonSchema.Data/Vocabularies.cs
- json-everything.net/Pages/Schema.razor
- json-everything.net/Services/AnchorRegistry.cs
- json-everything.net/wwwroot/md/release-notes/json-schema-data.md
- json-everything.net/wwwroot/md/vocabs-data-2022.md
- json-everything.net/wwwroot/meta/data-2022
Resolves some conversations with @handrews in the JSON Schema Slack workspace.
Change summary:
- instances are now referenced using either plain or relative JSON Pointers
- schema data is now referenced using JSON Pointer fragments without needing to specify the full URI
This brings `data` resolution in closer alignment with `$ref` (and potentially solves some other issues.
> Vocab data v2

- JsonSchema.Tests/Suite/Suite.cs
- JsonSchema/JsonSchema.csproj
- JsonSchema/SchemaRegistry.cs
- json-everything.net/wwwroot/md/release-notes/json-schema.md
> scan dynamically loaded schemas

- json-everything.net/wwwroot/md/release-notes/json-pointer.md
- json-everything.net/wwwroot/md/release-notes/json-schema-openapi.md
- json-everything.net/wwwroot/md/release-notes/json-schema-unique-keys.md
- json-everything.net/wwwroot/md/release-notes/json-schema.md
augments #326 
json-everything.net is deployed from draft-next so I don't want to post docs changes there quite yet.  This PR is a follow-up that allows me to update the docs without publishing the changes.
> Draft next docs

- JsonLogic.Tests/LessThanEqualTests.cs
- JsonLogic.Tests/LessThanTests.cs
- JsonLogic/Rules/LessThanEqualRule.cs
- JsonLogic/Rules/LessThanRule.cs
issue link -> https://github.com/gregsdennis/json-everything/issues/373
Between operator can handle operands that can be parse to a number.
Numberify values in case of 3 parameters passed into LessThenRule, LessThenEqualRule
> Update between operator

- README.md
I've just noticed the badge doesn't render correctly, so I went and copied the current markdown from GH Actions tab.
> docs: fix Build badge in README

- JsonSchema.Data/Vocabularies.cs
- JsonSchema.OpenApi.Tests/JsonSchema.OpenApi.Tests.csproj
- JsonSchema.OpenApi.Tests/OpenApiDoc.cs
- JsonSchema.OpenApi.Tests/Tests.cs
- JsonSchema.OpenApi/Vocabularies.cs
- JsonSchema.Tests/FormatTests.cs
- JsonSchema.Tests/VocabularyTests.cs
- JsonSchema.UniqueKeys/Vocabularies.cs
- JsonSchema/DynamicRefKeyword.cs
- JsonSchema/IBaseDocument.cs
- JsonSchema/JsonSchema.cs
- JsonSchema/JsonSchemaBuilder.cs
- JsonSchema/JsonSchemaBuilderExtensions.cs
- JsonSchema/RecursiveRefKeyword.cs
- JsonSchema/RefKeyword.cs
- JsonSchema/SchemaKeyword.cs
- JsonSchema/SchemaRegistry.cs
Resolves #355 
Relates to https://github.com/microsoft/OpenAPI.NET/issues/795
There are some comments in the code, but basically the `SchemaRegistry` now tracks `IBaseDocument`s instead of just `JsonSchema`s.  The `OpenApiDoc` (or whatever it'll be called) will need to:
- implement `IBaseDocument`
- register itself under a base URI
- perform an initialization scan to discover the schemas it contains
- set the document's base URI on every contained schema
It's a bit hacked together right now, but it works.
> Possible approach to support schemas nested in non-schema docs

- JsonSchema.Tests/FormatTests.cs
- JsonSchema/Formats.cs
DateTimes that have very high precision eg: 2023-03-20T05:41:23.802351665Z can be parsed by dotnet and are allowed by jsonschema but don't get accepted by TryParseExact
This uses regex as a fallback to check a datetime just incase it's actually compliant event though TryParseExact disagrees.
> date-time validation check using regex

- JsonPointer.Tests/GithubTests.cs
- JsonPointer/JsonPointer.cs
- JsonPointer/JsonPointer.csproj
- json-everything.net/wwwroot/md/release-notes/json-pointer.md
> jsonpointer - index out of range for array

- JsonSchema.Tests/DevTest.cs
- JsonSchema.Tests/Files/Issue435_schema.json
- JsonSchema.Tests/GithubTests.cs
- JsonSchema.Tests/JsonSchema.Tests.csproj
- JsonSchema/JsonSchema.cs
- JsonSchema/JsonSchema.csproj
- JsonSchema/RefKeyword.cs
- json-everything.net/wwwroot/md/release-notes/json-schema.md
Resolves #435 
Closes #430
I haven't been able to replicate this.  I've added .net 7 as a target and a test case with the reported schema/instance.
> Non-circular `$ref`

- JsonSchema.Generation.Tests/ArrayGenerationTests.cs
- JsonSchema.Generation.Tests/ClientTests.cs
- JsonSchema.Generation/ITypeNameGenerator.cs
- JsonSchema.Generation/JsonSchema.Generation.csproj
- JsonSchema.Generation/SchemaGenerationContextOptimizer.cs
- json-everything.net/wwwroot/md/release-notes/json-schema-generation.md
Resolves #455 
This will generate the following:
| Type | Generated Name |
|:-|:-|
| Guid | guid |
| MyType | myType |
| int | integer |
| int[] / List<int> / IEnumerable<int> | arrayOfInteger |
There may still be some oddiities, though.  There is also a new static property on `SchemaGenerationContextOptimizer` that allows the user to provide custom naming functionality.
> improved naming for $defs keys

- JsonPatch.Tests/PatchExtensionTests.cs
- JsonPatch/JsonPatch.cs
Json Source Generation requires that JsonConverter be public.  This is a small PR to make the PatchJsonConverter public to support source generation.
Reference:
https://learn.microsoft.com/en-us/dotnet/standard/serialization/system-text-json/source-generation
> add support for json source generation to JsonPatch

- Yaml2JsonNode.Tests/ClientTests.cs
- Yaml2JsonNode.Tests/Files/expected-serialized.yaml
- Yaml2JsonNode/Yaml2JsonNode.csproj
- Yaml2JsonNode/YamlConverter.cs
- tools/ApiDocsGenerator/release-notes/rn-yaml.md
Resolves #476 
This will set _all_ strings to have double-quotes unless the string itself has a double-quote, in which case it'll set for single-quotes.
> Set quote style for strings to support roundtrip

- Yaml2JsonNode.Tests/ClientTests.cs
- Yaml2JsonNode/Yaml2JsonNode.csproj
- Yaml2JsonNode/YamlConverter.cs
- tools/ApiDocsGenerator/release-notes/rn-yaml.md
> use invariant culture when parsing numbers from yaml data

- JsonSchema.Generation.Tests/ClientTests.cs
- JsonSchema.Generation/GeneratorRegistry.cs
- JsonSchema.Generation/Generators/JsonNodeSchemaGenerator.cs
- JsonSchema.Generation/JsonSchema.Generation.csproj
- tools/ApiDocsGenerator/release-notes/rn-json-schema-generation.md
> support `JsonNode` in schema generation

- JsonSchema/JsonNodeBaseDocument.cs
We've seen concurrency problems in `JsonNodeBaseDocument` that this should fix.
Example:
```
System.InvalidOperationException: Operations that change non-concurrent collections must have exclusive access. A concurrent update was performed on this collection and corrupted its state. The collection's state is no longer correct.
at System.Collections.Generic.Dictionary`2.FindValue(TKey key)
at System.Collections.Generic.Dictionary`2.TryGetValue(TKey key, TValue& value)
at Json.Schema.JsonNodeBaseDocument.FindSubschema(JsonPointer pointer, EvaluationOptions options)
at Json.Schema.RefKeyword.Evaluate(EvaluationContext context)
at Json.Schema.EvaluationContext.Evaluate()
```
> fix: make sure the sub schema cache is thread-safe for JsonNodeBaseDocument

- JsonPath/JsonPath.csproj
- JsonPath/SpanExtensions.cs
- tools/ApiDocsGenerator/release-notes/rn-json-path.md
Found via https://github.com/jsonpath-standard/jsonpath-compliance-test-suite/pull/50
> support for + in number literals

- JsonPatch.Tests/GithubTests.cs
- JsonPointer.Tests/ExpressionCreationTests.cs
- JsonPointer/JsonPointer.cs
- JsonPointer/JsonPointer.csproj
- JsonPointer/PointerCreationOptions.cs
- JsonPointer/PropertyNameResolvers.cs
- tools/ApiDocsGenerator/release-notes/rn-json-pointer.md
Resolves #542 
- Adds `.Last()` support to creation via linq expressions
- Adds naming options in parsing and creation methods
> Extended JSON Pointer support

- JsonSchema.Generation.Tests/ClientTests.cs
- JsonSchema.Generation/JsonSchema.Generation.csproj
- JsonSchema.Generation/TypeExtensions.cs
- tools/ApiDocsGenerator/release-notes/rn-json-schema-generation.md
> string does not have items

- Json.More.Tests/DevTest.cs
- Json.More.Tests/EqualityTests.cs
- Json.More/Json.More.csproj
- Json.More/JsonNodeExtensions.cs
- tools/ApiDocsGenerator/release-notes/rn-json-more.md
Found while implementing json-e.  Apparently `decimal` retains significant digits which becomes apparent when serialized in JSON.  This means that (for the purposes of the equality method) `4m == 4.0m` is false.
This PR updates the equality method to verify value equality for numbers specifically.
> Better number equality

- JsonSchema.Tests/FormatTests.cs
- JsonSchema/Formats.cs
Resolves https://github.com/gregsdennis/json-everything/issues/570.
The capturing group for `time-offset` (`([Zz]|[\+-]\d{2}:\d{2})`) has the quantifier `?` which allows it to occur zero times or once, effectively making it optional. Removing `?` ensures that it must occur exactly once.
> Make `time-offset` required for `date-time`

- JsonSchema.DataGeneration.Tests/StringGenerationTests.cs
- JsonSchema.DataGeneration/Generators/StringGenerator.cs
- JsonSchema.DataGeneration/HelperExtensions.cs
- JsonSchema.DataGeneration/JsonSchema.DataGeneration.csproj
- JsonSchema.DataGeneration/Requirements/StringRequirementsGatherer.cs
- JsonSchema.DataGeneration/RequirementsContext.cs
- tools/ApiDocsGenerator/release-notes/rn-json-schema-datageneration.md
Resolves #580 
This adds support for basically a single `pattern` keyword.  Combining `pattern` via `anyOf`/`allOf`/`oneOf` or inverting `pattern` via `not` is not supported.
> add limited support for pattern data generation

- JsonPath.Tests/TypeConverterTests.cs
- JsonPath/JsonPath.cs
- JsonPath/JsonPathTypeConverter.cs
- JsonPointer.Tests/TypeConverterTests.cs
- JsonPointer/JsonPointer.cs
- JsonPointer/JsonPointerTypeConverter.cs
Closes #585
This PR adds `TypeConverter` implementations for `JsonPointer` and `JsonPath` to allow instances of these types to be created via Microsoft's configuration binder.
> Add type converters for JsonPointer and JsonPath

- JsonSchema/ErrorMessages.cs
- JsonSchema/Formats.cs
- JsonSchema/JsonSchema.cs
I was looking into improving the performance of my application so I set up a scenario with `BenchmarkDotNet` which, using that particular schema, evaluated 1000 json documents. These changes reduce the time from 465 ms to 220 ms.
Here are the results from running `JsonSchema.Benchmark` on my machine.
Before:
```
|          Method |  n |       Mean |   Error |  StdDev |       Gen0 |       Gen1 | Allocated |
|---------------- |--- |-----------:|--------:|--------:|-----------:|-----------:|----------:|
| RunSuite_Legacy |  1 |   523.1 ms | 5.43 ms | 4.82 ms | 10000.0000 |  5000.0000 |  127.6 MB |
| RunSuite_Legacy | 10 | 1,249.4 ms | 6.08 ms | 5.08 ms | 63000.0000 | 16000.0000 | 754.56 MB |
```
After:
```
|          Method |  n |     Mean |   Error |  StdDev |       Gen0 |      Gen1 | …
```
> Performance improvement

- JsonSchema/JsonSchema.csproj
- JsonSchema/Localization/Resources.resx
- tools/ApiDocsGenerator/release-notes/rn-json-schema.md
Added missing space to `minProperties` resource string.
Related to PowerShell/PowerShell#21106.
> Add missing space to min properties error resx

- Json.More/Json.More.csproj
- Json.More/JsonSerializerOptionsExtensions.cs
- JsonLogic/JsonLogic.csproj
- JsonPatch/JsonPatch.csproj
- JsonPath/JsonPath.csproj
- JsonPointer/JsonPointer.csproj
- JsonSchema.ArrayExt/JsonSchema.ArrayExt.csproj
- JsonSchema.CodeGeneration/JsonSchema.CodeGeneration.csproj
- JsonSchema.CodeGeneration/Model/ModelGenerator.cs
- JsonSchema.Data/DataKeyword.cs
- JsonSchema.Data/JsonSchema.Data.csproj
- JsonSchema.Data/UriIdentifier.cs
- JsonSchema.OpenApi/DiscriminatorKeyword.cs
- JsonSchema.OpenApi/ExternalDocsKeyword.cs
- JsonSchema.OpenApi/JsonSchema.OpenApi.csproj
- JsonSchema.OpenApi/XmlKeyword.cs
- JsonSchema/ContainsKeyword.cs
- JsonSchema/ContentSchemaKeyword.cs
- JsonSchema/ErrorMessages.cs
- JsonSchema/EvaluationResults.cs
- JsonSchema/JsonNodeBaseDocument.cs
- JsonSchema/JsonSchema.cs
- JsonSchema/JsonSchema.csproj
- JsonSchema/JsonSerializerOptionsExtensions.cs
- JsonSchema/Serialization/ValidatingJsonConverter.cs
The downstream AOT callers can't see our #pragma warning disables. Need to use attributes so that people compiled against the library don't get messages about things we suppressed.
@sergio0694 can you take a peek too?
> Update pragma warning disables to SuppressMessage attributes

- JsonPatch/PatchResult.cs
This removes the nullability warning when writing code like 
```C#
if(!result.IsSuccess)
{
bool testOperationFailed = patchResult.Error.Contains("is not equal to the indicated value.");
}
```
This won't word before the library starts to (multi) target net5 or greater, but I still think it makes sense to have it ready as soon as that happens.
> Add [MemberNotNullWhen] to PatchResult

- JsonSchema/AdditionalItemsKeyword.cs
- JsonSchema/AdditionalPropertiesKeyword.cs
- JsonSchema/ContainsKeyword.cs
- JsonSchema/DependsOnAnnotationsFromAttribute.cs
- JsonSchema/ElseKeyword.cs
- JsonSchema/ItemsKeyword.cs
- JsonSchema/JsonSchema.csproj
- JsonSchema/ThenKeyword.cs
- JsonSchema/UnevaluatedItemsKeyword.cs
- JsonSchema/UnevaluatedPropertiesKeyword.cs
- tools/ApiDocsGenerator/release-notes/rn-json-schema.md
Apparently .Net Framework users are having trouble with the use of generic attributes in the library.
This reverts usage, but the generic attribute type is still there for those who want to create their own keywords and aren't using .Net Framework.
> use non-generic attributes internally

- JsonPath.Tests/JsonPath.Tests.csproj
- JsonPath.Tests/Suite/CburgmerFeatureValidationTests.cs
- JsonPath/Expressions/FunctionBooleanExpressionNode.cs
- JsonPath/Expressions/FunctionValueExpressionNode.cs
- JsonPath/Expressions/Operators.cs
- JsonPath/JsonPath.cs
- JsonPath/JsonPath.csproj
- JsonPath/PathSegment.cs
Resolves https://github.com/gregsdennis/json-everything/issues/652
Adds target framework for netstandard2.0 for JsonPath.Net
> Add support for .NET Standard 2.0 for JsonPath.Net

- JsonPath.Tests/SerializerOptions.cs
- JsonPath.Tests/Suite/ComplianceTestCase.cs
- JsonPath.Tests/Suite/ComplianceTestSuiteTests.cs
Depends on https://github.com/jsonpath-standard/jsonpath-compliance-test-suite/pull/60
> update JSON Path test runner for non-deterministic tests

- JsonPath.Tests/ExpressionTests.cs
- JsonPath.Tests/ParsingTests.cs
- JsonPath/Expressions/BinaryLogicalExpressionNode.cs
- JsonPath/Expressions/ValueExpressionNode.cs
- JsonPath/JsonPath.csproj
- tools/ApiDocsGenerator/release-notes/rn-json-path.md
Relates to https://github.com/jsonpath-standard/jsonpath-compliance-test-suite/pull/64
> fixed issue with building boolean expression trees; updated path test suite

- JsonSchema/EvaluationResults.cs
- JsonSchema/JsonSchema.csproj
- json-everything.net/Pages/Schema.razor
- tools/ApiDocsGenerator/release-notes/rn-json-schema.md
Closes #694 
I've opted to just obsolete the converter.  There are a number of technical issues that make fixing this more effort than it's worth.  The 2019-09/2020-12 output is poorly specified anyway.
> obsolete 2020 output converter

- JsonE.Tests/Files/more-tests.yml
- JsonE/Operators/IfThenElseOperator.cs
- JsonE/Operators/SwitchOperator.cs
Resolves #713
The samples for json-e indicate that one can check for an value in an if statement and attempt to use it in the 'then' block.
This change delays evaluating the 'then' and 'else' blocks until they are needed, and a similar change is applied to the 'switch' statement.
The change for `IfThenElseOperator` is fairly straightforward. The `SwitchOperator` one was as well, although it does change the order from:
1. Evaluate parameter dictionary (`JsonE.Evaluate(parameter, context)!.AsObject();`)
2. Check truthiness
3. Copy value
to:
1. Iterate over parameter dictionary (keys have not yet went to `JsonE.Evaluate`! Not sure if this is important. I saw one code path that looked like it might unescape keys or impact it another way. Please review carefully.)
2. Check truthiness
3. …
> Do not evaluate untaken if and switch branches

- JsonLogic/JsonLogic.csproj
- JsonLogic/RuleRegistry.cs
- JsonSchema/JsonSchema.csproj
- JsonSchema/SchemaKeywordRegistry.cs
- tools/ApiDocsGenerator/release-notes/rn-json-logic.md
- tools/ApiDocsGenerator/release-notes/rn-json-schema.md
Missed this type rename during the AOT update.
> fix an exception message

- JsonPath/JsonPath.csproj
- JsonPath/UtilityExtensions.cs
- tools/ApiDocsGenerator/release-notes/rn-json-path.md
Related to https://github.com/jsonpath-standard/jsonpath-compliance-test-suite/pull/35
> Fix matching on unicode to ignore newlines

- JsonPath/JsonPath.csproj
- JsonPath/UtilityExtensions.cs
- JsonSchema/CommonJsonPointers.cs
- JsonSchema/JsonSchema.csproj
- tools/ApiDocsGenerator/release-notes/rn-json-path.md
- tools/ApiDocsGenerator/release-notes/rn-json-schema.md
Addresses failures discovered by https://github.com/jsonpath-standard/jsonpath-compliance-test-suite/pull/77
Resolves #726
> update test suite

- src/JsonPath/JsonPath.csproj
- src/JsonPath/SpanExtensions.cs
- tools/ApiDocsGenerator/release-notes/rn-json-path.md
Depends on https://github.com/jsonpath-standard/jsonpath-compliance-test-suite/pull/78
Resolves #728
> quote escapes in filter expressions

- src/JsonPath/FunctionRepository.cs
Fix AOT trim warning from JsonPath (`'this' argument does not satisfy 'DynamicallyAccessedMemberTypes.PublicMethods' in call to 'System.Type.GetMethods(BindingFlags)'. The return value of method 'System.Object.GetType()' does not have matching annotations.`).
* Added annotations to FindEvaluationMethods (internal method)
* Added new public APIs with overloads that have the appropriate AOT annotations.
I didn't file a separate issue to report this.
I was trying out JsonPath in an AOT project and hit a trim warning during publish:
```
src\JsonPath\FunctionRepository.cs(94,17,94,85): warning IL2075: 'this' argument does not satisfy 'DynamicallyAccessedMemberTypes.PublicMethods' in call to 'System.Type.GetMethods(BindingFlags)'. The return value of method 'System.Object.GetType()' does not …
```
> Address AOT Trim warning in JsonPath

- src/JsonPath/Expressions/InOperator.cs
> chore: Fix typo in InOperator

- src/JsonSchema/EvaluationOptions.cs
- src/JsonSchema/JsonSchema.cs
- src/JsonSchema/JsonSchema.csproj
- tools/ApiDocsGenerator/release-notes/rn-json-schema.md
Adds `EvaluationOptions.AllowReferencesIntoUnknownKeywords` to optionally disallow `$ref` navigation into unknown keywords.
Relates to https://github.com/json-schema-org/json-schema-spec/issues/1528 / https://github.com/json-everything/json-everything/issues/753
> add evaluation option to disallow unknown keyword $ref navigation

- .github/workflows/dotnet-core.yml
- src/JsonPointer/JsonPointer.csproj
- src/JsonSchema/AllOfKeyword.cs
- src/JsonSchema/AnyOfKeyword.cs
- src/JsonSchema/DependentSchemasKeyword.cs
- src/JsonSchema/EvaluationContext.cs
- src/JsonSchema/JsonSchema.cs
- src/JsonSchema/PatternPropertiesKeyword.cs
- src/JsonSchema/PropertiesKeyword.cs
- src/JsonSchema/PropertyDependenciesKeyword.cs
- tools/ApiDocsGenerator/release-notes/rn-json-pointer.md
For some reason the DLL published to nuget seems to be missing `.GetAncestor()` and `.GetLocal()`.  Not sure why.
Relates to https://github.com/gregsdennis/Graeae/pull/6
> JsonPointer.Net missing methods

- src/JsonPatch.Tests/PatchExtensionTests.cs
- src/JsonPatch/JsonPatch.csproj
- src/JsonPointer.Tests/JsonPointerParseTests.cs
- src/JsonPointer/JsonPointer.cs
- src/JsonPointer/JsonPointer.csproj
- src/JsonPointer/SpanExtensions.cs
- src/JsonSchema/JsonSchema.csproj
- tools/ApiDocsGenerator/release-notes/rn-json-patch.md
- tools/ApiDocsGenerator/release-notes/rn-json-pointer.md
- tools/ApiDocsGenerator/release-notes/rn-json-schema.md
When building a JSON Pointer using `JsonPointer.Create()`, `.ToString()` doesn't escape segments.
Resolves #754
> JSON Pointer escapes not honored when pointer is constructed instead of parsed

- src/JsonSchema.Generation.Tests/ClientTests.cs
- src/JsonSchema.Generation/JsonSchema.Generation.csproj
- src/JsonSchema.Generation/XmlComments/XmlDocId.cs
- tools/ApiDocsGenerator/release-notes/rn-json-schema-generation.md
The `[Description]` attribute and the resulting `description` keyword can be improved.  There are some complications around optimizations and the attribute being able to appear on both the property and the type.
Currently exploring options.
Resolves #767
Relates to #769
> Descriptions for deeply nested types not added to schema generation

- src/JsonPath/Expressions/EqualToOperator.cs
- src/JsonPath/Expressions/NotEqualToOperator.cs
- src/JsonPath/IPathFunctionDefinition.cs
- src/JsonPath/JsonPath.csproj
- src/JsonPath/NameSelector.cs
- tools/ApiDocsGenerator/release-notes/rn-json-path.md
- updated test suite
- fixed equality of nothing
- fixed `\u` parsing
- Relates to https://github.com/jsonpath-standard/jsonpath-compliance-test-suite/pull/84
- Relates to https://github.com/jsonpath-standard/jsonpath-compliance-test-suite/pull/86
> updated test suite; fixed equality of nothing; fixed `\u` parsing

- src/JsonPath/JsonPath.csproj
- src/JsonPath/NameSelector.cs
- src/JsonPath/SpanExtensions.cs
- tools/ApiDocsGenerator/release-notes/rn-json-path.md
More updates to the JSON Path test suite found more bugs.  Thanks to [@Marcono1234](https://github.com/Marcono1234) for adding these scenarios.
Relates to https://github.com/jsonpath-standard/jsonpath-compliance-test-suite/pull/87
Depends on https://github.com/jsonpath-standard/jsonpath-compliance-test-suite/pull/88
Depends on https://github.com/jsonpath-standard/jsonpath-compliance-test-suite/pull/89
Depends on https://github.com/jsonpath-standard/jsonpath-compliance-test-suite/pull/90
> Handle more updates to JSON Path test suite

- src/JsonSchema.DataGeneration/Generators/StringGenerator.cs
- src/JsonSchema.DataGeneration/Requirements/StringRequirementsGatherer.cs
- src/JsonSchema.DataGeneration/RequirementsContext.cs
- src/JsonSchema/AnchorKeyword.cs
- src/JsonSchema/Formats.cs
- src/JsonSchema/JsonSchemaBuilderExtensions.cs
- src/JsonSchema/JsonSchemaExtensions.KeywordAccess.cs
- src/JsonSchema/PatternKeyword.cs
- src/JsonSchema/PatternPropertiesKeyword.cs
- src/JsonSchema/RegexFormat.cs
- src/JsonSchema/RegexOrPattern.cs
Improved usage of `Regex` in several places.
When a `string` pattern is supplied for `Pattern` or `PatterProperties` keywords, the static `Regex.IsMatch` will be used to evaluate the keywords. 
When a `Regex` instance is supplied, that instance is used by the keywords.
I also made the `_dateTimeRegex` a compiled regex to improve performance. (this could be improved further by using code generated regex instances.)
Updated the `Formats` class to use code generated regex if possible.
* The return type of `JsonSchemaExtensions.KeywordAccess` `GetPattern` and `GetPatternProperties` will return the `string` pattern and not the `Regex` instance.
* The  `Regex Value` property in the `PatternKeyword` was removed, in favor of a `string Pattern` property. 
* The `PatternPropertiesKeyword.Patterns` …
> Improve performance of regex usage in JsonSchema

- src/JsonSchema/EvaluationContext.cs
- src/JsonSchema/JsonSchema.cs
- src/JsonSchema/JsonSchema.csproj
- src/JsonSchema/SchemaRegistry.cs
- tools/ApiDocsGenerator/release-notes/rn-json-schema.md
- tools/Benchmarks/SchemaSuite/TestSuiteRunner.cs
Schemas which have more than 512 subschemas will throw an `IndexOutOfRangeException` during registration.
cc: @Laniusexcubitor
Resolves #778
> Count subschemas before memory allocation

- src/JsonSchema.Tests/OutputTests.cs
- src/JsonSchema/JsonSchema.csproj
- src/JsonSchema/UnevaluatedItemsKeyword.cs
- src/JsonSchema/UnevaluatedPropertiesKeyword.cs
- tools/ApiDocsGenerator/release-notes/rn-json-schema.md
The `unevaluated*` keywords are duplicating their pointer segment for the instance location in the output.
> unevaluated* duplicating pointer segments in instance location

- .github/workflows/publish-schema.yml
- src/JsonSchema.Tests/GithubTests.cs
- src/JsonSchema.Tests/TestSerializerContext.cs
- src/JsonSchema/Serialization/ValidatingJsonConverter.cs
Fixes an issue with mapping external types into the validating serialization converter.
Resolves #791
> Fix issue with validating serialization converter

- src/JsonSchema.Generation/Attributes/JsonExcludeAttribute.cs
In the previous PR that added the ability to skip enum members from schema generation, I didn't update the XML doc of `JsonExclude`. The generated docs would be missing this bit.
Fully resolves issue https://github.com/json-everything/json-everything/issues/795
Depends on PR https://github.com/json-everything/json-everything/pull/796
- [ X] I have read and understand the [Code of Conduct](https://github.com/json-everything/json-everything/blob/master/CODE_OF_CONDUCT.md) and [Contribution Guidelines](https://github.com/json-everything/json-everything/blob/master/CONTRIBUTING.md).
> Updated XML doc on JsonExclude

- src/JsonE.Tests/CustomFunctionTests.cs
- src/JsonE/EvaluationContext.cs
- src/JsonE/Expressions/Functions/RangeFunction.cs
- src/JsonE/Expressions/Operators/NegateOperator.cs
- src/JsonE/Expressions/Operators/PosateOperator.cs
- src/JsonE/JsonE.csproj
- src/JsonE/JsonNodeExtensions.cs
- src/JsonE/Operators/CommonErrors.cs
- src/JsonE/Operators/FindOperator.cs
- src/JsonE/Operators/MapOperator.cs
- src/JsonE/Operators/OperatorRepository.cs
- src/JsonE/Operators/ReduceOperator.cs
- tools/ApiDocsGenerator/release-notes/rn-json-e.md
Adds the new `$reduce` operator and `range()` function.
Resolves #804
Relates to https://github.com/json-e/json-e/pull/531 & https://github.com/json-e/json-e/pull/534
> JSON-e - $reduce & range()

- src/JsonPatch.Tests/GithubTests.cs
- src/JsonPatch/CopyOperationHandler.cs
- src/JsonPatch/JsonPatch.csproj
- tools/ApiDocsGenerator/release-notes/rn-json-patch.md
Missing fix for issue #825 
It was not possible to copy an item to the end of an array.
Relates to  #825
> fix: make copy with '-' as target working

- src/JsonPatch.Tests/GithubTests.cs
- src/JsonPatch/JsonPatch.csproj
- src/JsonPatch/RemoveOperationHandler.cs
- src/JsonPatch/ReplaceOperationHandler.cs
- tools/ApiDocsGenerator/release-notes/rn-json-patch.md
Unfortunately, I missed two more places with the same issue...
This PR makes the following syntax possible for the patch operations remove and replace: `/Items/-`
It will then remove or replace the last element in the array.
---
I have also removed the logic in the replace operation to add new elements to the array.
Until now the following was possible (pseudo-code):
```
array = [1, 2, 3]
array = array.Replace("/Items/3", 4)
array --> [1, 2, 3, 4]
```
According to the [JsonPatch specification](https://datatracker.ietf.org/doc/html/rfc6902#section-4.3) for the replacement operation: `The target location MUST exist for the operation to be successful.`
It should therefore not be possible to reference a not existing index of the array.
#825
> fix: make end of array via '-' accessible

- src/JsonSchema/Localization/Resources.ko.resx
- src/JsonSchema/nuspec/JsonSchema.Net.ko.nuspec
- src/JsonSchema/nuspec/README.ko.md
This PR adds a Korean translation of JsonSchema.Net to make it easier for Korean speakers to understand error messages.
Nothing
> Add Korean Localization

- src/JsonSchema.Tests/DependencyChecks.cs
- src/JsonSchema/JsonSchema.csproj
- src/JsonSchema/nuspec/JsonSchema.Net.nuspec
Adds a dependency check that will fail when nuspec file for `JsonSchema.Net` isn't aligned with latest lib versions.
Resolves #844
> add dependency check for jsonschema.net

- src/JsonPointer.Tests/JsonPointerParseTests.cs
- src/JsonPointer.Tests/JsonPointerTests.cs
- src/JsonPointer/JsonPointer.cs
- src/JsonPointer/JsonPointer.csproj
- src/JsonPointer/SpanExtensions.cs
- src/JsonSchema.Tests/LocalizationTests.cs
- src/JsonSchema.Tests/OutputTests.cs
- src/JsonSchema/nuspec/JsonSchema.Net.nuspec
- tools/ApiDocsGenerator/release-notes/rn-json-pointer.md
- tools/Benchmarks/Pointer/Runner.cs
- tools/Benchmarks/Program.cs
Properly disposes of the rented memory, and also sets the minimum buffer size when renting, to avoid (some) buffer resizings, since we already have the segment length at hand.
Fixes #849
> Properly dispose of rented memory in JsonPointer.ToString()

- src/Json.More.Tests/EnumStringConverterTests.cs
- src/Json.More/EnumStringConverter.cs
- src/Json.More/Json.More.csproj
- tools/ApiDocsGenerator/release-notes/rn-json-more.md
Allow enum serialization with duplicated member values.
This does not affect the public API surface;
The changes does not cause breaks in either developer experience or behavior;
Resolves  #856
> fix #856; allow enum serialization with duplicated member values

- src/JsonSchema.Generation/XmlComments/DocXmlReader.cs
- tools/ApiDocsGenerator/release-notes/rn-json-schema-generation.md
Fix a typo of SchemaGeneratorConfiguration instead of SchemaGenerationConfiguration.
As discussed in the docs repository.
Relates to https://github.com/json-everything/json-everything-docs/pull/23
> Fix typo 'SchemaGeneratorConfiguration'

- src/JsonPointer/JsonPointer.cs
- src/JsonPointer/JsonPointer.csproj
- src/JsonPointer/PointerSegment.cs
- src/JsonPointer/RelativeJsonPointer.cs
- src/JsonPointer/UtilityExtensions.cs
- tools/ApiDocsGenerator/release-notes/rn-json-pointer.md
Use modern Span-based APIs to avoid allocations when parsing RelativeJsonPointer
Resolves #863 
Depends on #868
> RelativeJsonPointer: use span APIs when on .NET8+

- src/Json.More.Tests/JsonArrayTupleConverterDeserializationTests.cs
- src/Json.More.Tests/JsonArrayTupleConverterSerializationTests.cs
- src/Json.More/Json.More.csproj
- src/Json.More/JsonArrayTupleConverter.cs
- tools/ApiDocsGenerator/release-notes/rn-json-more.md
JsonArrayTupleConverter was attempting to serialise/deserialise arrays of tuples, causing a crash. Now it will no longer consider arrays of tuples as a valid type to serialise, so the following code will now serialise/deserialise correctly.
```c#
var result = JsonSerializer.Deserialize<(int, bool)[]>(
"[[1,true],[2,false]]",
new JsonSerializerOptions()
{
Converters =
{
new JsonArrayTupleConverter(),
}
});
``` 
Resolves https://github.com/json-everything/json-everything/issues/885
> JsonArrayTupleConverter is no longer valid for arrays of tuples.

- src/JsonSchema.Generation.Tests/PropertyOverridesTests.cs
- src/JsonSchema.Generation/Generators/ObjectSchemaGenerator.cs
- src/JsonSchema.Generation/JsonSchema.Generation.csproj
- tools/ApiDocsGenerator/release-notes/rn-json-schema-generation.md
This fixes the issue #897 , where a type with a property override using 'new' keyword would throw an exception when trying to generate the json schema.
Resolves #897
> Fix schema generation for property override with 'new' keyword  #897

- src/JsonLogic.Tests/Files/more-tests.json
- src/JsonLogic/JsonLogic.csproj
- src/JsonLogic/Rules/AndRule.cs
- src/JsonLogic/Rules/OrRule.cs
- tools/ApiDocsGenerator/release-notes/rn-json-logic.md
Operators And and Or have lost feature to return the last argument with applied rules in IRule implementation
Resolves https://github.com/json-everything/json-everything/issues/922
> Fix for operators And and Or
