JsonSchema.Tests/SerializationTests.cs, JsonSchema/ElseKeyword.cs, JsonSchema/JsonSchema.csproj, JsonSchema/ReadOnlyKeyword.cs, JsonSchema/ThenKeyword.cs, docs_source/release-notes/json-schema.md
=> Some bug fixes

Json.More/Json.More.xml, JsonSchema.Tests/OutputTests.cs, JsonSchema/Annotation.cs, JsonSchema/JsonSchema.Net.xml, JsonSchema/JsonSchema.cs, JsonSchema/JsonSchema.csproj, JsonSchema/RefKeyword.cs, JsonSchema/ValidationContext.cs, JsonSchema/ValidationResults.cs, docs_source/release-notes/json-schema.md
=> Exclude nodes from detailed output

JsonSchema.Tests/OutputTests.cs, JsonSchema.Tests/ResultsExtensions.cs, JsonSchema/JsonSchema.cs, JsonSchema/ValidationContext.cs, JsonSchema/ValidationResults.cs, docs_source/release-notes/json-schema.md
=> remove the notion of a result node being required; don't copy isvalid

JsonSchema.Tests/Files/issue29-schema-with-id.json, JsonSchema.Tests/Files/issue29-schema-without-id.json, JsonSchema.Tests/GithubTests.cs, JsonSchema.Tests/JsonSchema.Tests.csproj, JsonSchema.Tests/OutputTests.cs, JsonSchema.Tests/ResultsExtensions.cs, JsonSchema/IdKeyword.cs, JsonSchema/JsonSchema.Net.xml, JsonSchema/JsonSchema.cs, JsonSchema/JsonSchema.csproj, JsonSchema/ValidationContext.cs, JsonSchema/ValidationOptions.cs, JsonSchema/ValidationResults.cs, docs_source/release-notes/json-schema.md
=> Version 1.4.0

docs_source/usage/schema/validation.md
Fixed several errors I noticed with the validation example.
=> Fixed validation example errors.

JsonSchema/EnumKeyword.cs
=> Fix enum keyword

.github/label-config.yml, .github/workflows/dotnet-core.yml, .github/workflows/publish-schema-data.yml, Json.More/Json.More.xml, JsonLogic/JsonLogic.xml, JsonSchema.Data.Tests/JsonSchema.Data.Tests.csproj, JsonSchema.Data.Tests/Tests.cs, JsonSchema.Data/DataKeyword.cs, JsonSchema.Data/JsonSchema.Data.csproj, JsonSchema.Data/JsonSchema.Net.Data.xml, JsonSchema.Data/JsonSchemaBuilderExtensions.cs, JsonSchema.Data/MetaSchemas.cs, JsonSchema.Data/Vocabularies.cs, JsonSchema.Generation.Tests/JsonSchema.Generation.Tests.csproj, JsonSchema/JsonSchema.Net.xml, JsonSchema/JsonSchema.csproj, JsonSchema/UriExtensions.cs, docs_source/docfx.json, docs_source/release-notes/json-schema-data.md, docs_source/release-notes/json-schema-generation.md, docs_source/release-notes/json-schema.md, docs_source/release-notes/toc.yml, docs_source/usage/meta/data.json, docs_source/usage/toc.yml, docs_source/usage/vocabs-data.md, json-everything.sln
This is really just an idea, but it works, so... why not?
=> Vocab data

.github/label-config.yml, JsonLogic/JsonElementExtensions.cs, JsonLogic/JsonLogic.csproj, JsonLogic/JsonLogic.xml, JsonLogic/RuleRegistry.cs, JsonPath/SpanExtensions.cs, JsonSchema.Generation/JsonSchema.Net.Generation.xml, JsonSchema.Tests/VocabularyTests.cs, JsonSchema/AnchorKeyword.cs, JsonSchema/DynamicAnchorKeyword.cs, JsonSchema/DynamicRefKeyword.cs, JsonSchema/IAnchorProvider.cs, JsonSchema/IdKeyword.cs, JsonSchema/JsonSchema.Net.xml, JsonSchema/JsonSchema.cs, JsonSchema/JsonSchema.csproj, JsonSchema/SchemaKeyword.cs, JsonSchema/SchemaRegistry.cs, JsonSchema/ValidationContext.cs, JsonSchema/ValidationOptions.cs, JsonSchema/VocabularyRegistry.cs, docs_source/release-notes/json-logic.md, docs_source/release-notes/json-patch.md, docs_source/release-notes/json-path.md, docs_source/release-notes/json-pointer.md, docs_source/release-notes/json-schema.md, docs_source/usage/json-logic.md
Resolves #91 and updates JSON Schema test suite (and fixes the schema library)
=> update docs; expose element extensions

JsonSchema.Generation.Tests/SchemaGenerationTests.cs, JsonSchema.Generation/JsonSchema.Generation.csproj, JsonSchema.Generation/JsonSchema.Net.Generation.xml, JsonSchema.Generation/SchemaGeneratorContext.cs, docs_source/release-notes/json-schema-generation.md
=> Leave simple schemas

JsonSchema.Generation/JsonSchema.Net.Generation.xml, JsonSchema/ContainsKeyword.cs, JsonSchema/JsonSchema.csproj, JsonSchema/MaxContainsKeyword.cs, JsonSchema/MinContainsKeyword.cs, JsonSchema/UnevaluatedItemsKeyword.cs, docs_source/release-notes/json-schema.md
depends on https://github.com/json-schema-org/JSON-Schema-Test-Suite/pull/479
=> unevaluatedItems should consider contains; updated version and release notes

Json.More/EnumStringConverter.cs, Json.More/Json.More.csproj, JsonSchema.Generation.Tests/SchemaGenerationTests.cs, JsonSchema.Generation/Generators/ObjectSchemaGenerator.cs, JsonSchema.Generation/JsonSchema.Generation.csproj, docs_source/release-notes/json-more.md, docs_source/release-notes/json-schema-generation.md
Thanks to @jaysvoboda for #104
=> Schemagen more release

JsonSchema.Generation.Tests/AssertionExtensions.cs, JsonSchema.Generation.Tests/GeneratorTests.cs, JsonSchema.Generation.Tests/SchemaGenerationTests.cs, JsonSchema.Generation/GeneratorRegistry.cs, JsonSchema.Generation/Generators/EnumDictionarySchemaGenerator.cs, JsonSchema.Generation/Intents/PropertyNamesIntent.cs, JsonSchema.Generation/JsonSchema.Generation.csproj, JsonSchema.Generation/JsonSchema.Net.Generation.xml, docs_source/release-notes/json-schema-generation.md
=> Issue 114 datetime schemagen

JsonSchema.Generation.Tests/PropertyNamingTests.cs, JsonSchema.Generation/Generators/ObjectSchemaGenerator.cs, JsonSchema.Generation/JsonSchema.Generation.csproj, JsonSchema.Generation/JsonSchema.Net.Generation.xml, JsonSchema.Generation/PropertyNamingMethods.cs, JsonSchema.Generation/SchemaGeneratorConfiguration.cs, JsonSchema/IdKeyword.cs, JsonSchema/JsonSchema.cs, JsonSchema/JsonSchema.csproj, JsonSchema/RefKeyword.cs, JsonSchema/SchemaRegistry.cs, JsonSchema/ValidationContext.cs, JsonSchema/ValidationOptions.cs, docs_source/release-notes/json-schema-generation.md, docs_source/release-notes/json-schema.md, docs_source/usage/schema-generation.md
=> Schemagen camel case

.github/workflows/dotnet-core.yml, Json.More/Utf8JsonWriterExtensions.cs
this shouldn't post analysis reports
=> added steps to check for changes

JsonSchema.Generation.Tests/SchemaGenerationTests.cs, JsonSchema.Generation/DescriptionAttribute.cs, JsonSchema.Generation/ExclusiveMaximumAttribute.cs, JsonSchema.Generation/ExclusiveMinimumAttribute.cs, JsonSchema.Generation/Generators/ObjectSchemaGenerator.cs, JsonSchema.Generation/Intents/DescriptionIntent.cs, JsonSchema.Generation/Intents/TitleIntent.cs, JsonSchema.Generation/JsonExcludeAttribute.cs, JsonSchema.Generation/JsonSchema.Generation.csproj, JsonSchema.Generation/JsonSchema.Net.Generation.xml, JsonSchema.Generation/MaximumAttribute.cs, JsonSchema.Generation/MinimumAttribute.cs, JsonSchema.Generation/SchemaGeneratorConfiguration.cs, JsonSchema.Generation/TitleAttribute.cs, docs_source/release-notes/json-schema-generation.md, docs_source/usage/schema-generation.md
=> Schemagen metadata

JsonPatch/JsonPatch.csproj, JsonPatch/PatchOperation.cs, JsonSchema.Generation/JsonNumberHandlingAttributeHandler.cs, JsonSchema.Generation/JsonSchema.Net.Generation.xml, docs_source/release-notes/json-patch.md
=> fixed issue with deserialization in mvc

JsonPath.Tests/GithubTests.cs, JsonPath/JsonPath.csproj, JsonPath/SpanExtensions.cs, docs_source/release-notes/json-path.md
=> Path issue150 parsing numbers with 9

JsonPath.Tests/OtherParsingTests.cs, JsonPath/JsonPath.csproj, JsonPath/QueryExpressions/AdditionOperator.cs, JsonPath/QueryExpressions/AndOperator.cs, JsonPath/QueryExpressions/DivisionOperator.cs, JsonPath/QueryExpressions/EqualToOperator.cs, JsonPath/QueryExpressions/ExistsOperator.cs, JsonPath/QueryExpressions/GreaterThanOperator.cs, JsonPath/QueryExpressions/GreaterThanOrEqualToOperator.cs, JsonPath/QueryExpressions/IQueryExpressionOperator.cs, JsonPath/QueryExpressions/LessThanOperator.cs, JsonPath/QueryExpressions/LessThanOrEqualToOperator.cs, JsonPath/QueryExpressions/ModulusOperator.cs, JsonPath/QueryExpressions/MultiplicationOperator.cs, JsonPath/QueryExpressions/NotEqualToOperator.cs, JsonPath/QueryExpressions/NotOperator.cs, JsonPath/QueryExpressions/Operators.cs, JsonPath/QueryExpressions/OrOperator.cs, JsonPath/QueryExpressions/QueryExpressionNode.cs, JsonPath/QueryExpressions/SubtractionOperator.cs, JsonPath/SpanExtensions.cs, docs_source/release-notes/json-path.md
Related to https://github.com/ietf-wg-jsonpath/draft-ietf-jsonpath-base/issues/119
=> support for the unary-not syntax

JsonSchema/JsonSchema.csproj, JsonSchema/MinItemsKeyword.cs, JsonSchema/MinPropertiesKeyword.cs, docs_source/release-notes/json-schema.md
=> fixed copy/paste error in minproperties

Json.More.Tests/Json.More.Tests.csproj, JsonLogic.Tests/JsonLogic.Tests.csproj, JsonPatch.Tests/JsonPatch.Tests.csproj, JsonPath.Tests/JsonPath.Tests.csproj, JsonPointer.Benchmark/JsonPointer.Benchmark.csproj, JsonPointer.Tests/JsonPointer.Tests.csproj, JsonSchema.Data.Tests/JsonSchema.Data.Tests.csproj, JsonSchema.Generation.Tests/JsonSchema.Generation.Tests.csproj, JsonSchema.Generation/JsonSchema.Generation.csproj, JsonSchema.Tests/JsonSchema.Tests.csproj, JsonSchema.Tests/MetaTests.cs, JsonSchema.UniqueKeys.Tests/JsonSchema.UniqueKeys.Tests.csproj, JsonSchema/JsonSchema.cs, JsonSchema/JsonSchema.csproj, JsonSchema/SchemaRegistry.cs, JsonSchema/ValidationOptions.cs, docs_source/release-notes/json-schema-generation.md, docs_source/release-notes/json-schema.md
=> Schema v1.11.4

JsonPatch.Tests/PatchExtensionTests.cs, JsonPatch.Tests/SingleOpProcessingTests.cs, JsonPatch.Tests/Suite/JsonPatchTest.cs, JsonPatch.Tests/Suite/JsonPatchTestSuite.cs, JsonPatch/JsonPatch.csproj, JsonPatch/PatchOperation.cs, JsonPointer/JsonPointer.cs, JsonPointer/JsonPointer.csproj, JsonPointer/JsonPointerJsonConverter.cs, JsonPointer/PointerSegment.cs, JsonPointer/RelativeJsonPointer.cs, JsonPointer/RelativeJsonPointerJsonConverter.cs, JsonSchema/DynamicRefKeyword.cs, JsonSchema/JsonSchema.csproj, JsonSchema/ValidationResults.cs, docs_source/release-notes/json-patch.md, docs_source/release-notes/json-pointer.md, docs_source/release-notes/json-schema.md, docs_source/release-notes/toc.yml, json-everything.sln.DotSettings
=> updated jsonpointer from struct to class

JsonLogic/JsonLogic.csproj, JsonPath/JsonPath.csproj, JsonSchema.Data/JsonSchema.Data.csproj, JsonSchema.Generation/JsonSchema.Generation.csproj, JsonSchema.UniqueKeys/JsonSchema.UniqueKeys.csproj, docs_source/release-notes/json-logic.md, docs_source/release-notes/json-path.md, docs_source/release-notes/json-schema-data.md, docs_source/release-notes/json-schema-generation.md, docs_source/release-notes/json-schema-unique-keys.md
=> update other packages after pointer update

JsonPointer.Tests/ExpressionCreationTests.cs, JsonPointer/JsonPointer.cs, JsonPointer/JsonPointer.csproj, docs_source/release-notes/json-pointer.md
=> Issue184 array support for pointers

JsonSchema.Tests/FormatTests.cs, JsonSchema/FormatKeyword.cs, JsonSchema/JsonSchema.csproj, JsonSchema/UnknownFormat.cs, JsonSchema/ValidationOptions.cs, docs_source/release-notes/json-schema.md
=> unknown format validations should not error

JsonLogic.Tests/ExtensionTests.cs, JsonLogic.Tests/GithubTests.cs, JsonLogic.Tests/JsonAssert.cs, JsonLogic.Tests/NotTests.cs, JsonLogic/JsonElementExtensions.cs, JsonLogic/JsonLogic.csproj, JsonLogic/Rule.cs, JsonLogic/Rules/RuleCollection.cs, docs_source/release-notes/json-logic.md
Relates to #183 (partially resolves)
=> Logic arrays

JsonSchema.Tests/BundlingTests.cs, JsonSchema/IdKeyword.cs, JsonSchema/JsonSchema.cs, JsonSchema/JsonSchema.csproj, JsonSchema/JsonSchemaBuilderExtensions.cs, JsonSchema/SchemaKeyword.cs, JsonSchema/ValidationContext.cs, docs_source/release-notes/json-schema.md
=> Issue 207 schema bundling broken

JsonSchema.Tests/GithubTests.cs, JsonSchema/JsonSchema.cs, JsonSchema/ValidationContext.cs, docs_source/release-notes/json-schema.md
=> Bundled schemas containing references to internal definitions

JsonSchema.Tests/Files/issue212_schema.json, JsonSchema.Tests/GithubTests.cs, JsonSchema/JsonSchema.cs, JsonSchema/JsonSchema.csproj, JsonSchema/ValidationContext.cs, docs_source/release-notes/json-schema.md
Depends on #214 
Resolves #208
=> schema v2.0.2

JsonSchema.Tests/GithubTests.cs, JsonSchema/AdditionalPropertiesKeyword.cs, JsonSchema/JsonSchema.csproj, JsonSchema/ValidationOptions.cs, docs_source/release-notes/json-schema.md
=> Issue216 additionalitems error not expected

JsonSchema.Tests/Files/Issue226_instance.json, JsonSchema.Tests/Files/Issue226_schema.json, JsonSchema.Tests/GithubTests.cs, JsonSchema/JsonSchema.csproj, JsonSchema/ValidationResults.cs, docs_source/release-notes/json-schema.md
=> Issue226 error in passing results

JsonSchema.Tests/GithubTests.cs, JsonSchema/AdditionalItemsKeyword.cs, JsonSchema/AdditionalPropertiesKeyword.cs, JsonSchema/AllOfKeyword.cs, JsonSchema/AnyOfKeyword.cs, JsonSchema/ContainsKeyword.cs, JsonSchema/ContentSchemaKeyword.cs, JsonSchema/DefinitionsKeyword.cs, JsonSchema/DefsKeyword.cs, JsonSchema/DependenciesKeyword.cs, JsonSchema/DependentSchemasKeyword.cs, JsonSchema/ElseKeyword.cs, JsonSchema/IRefResolvable.cs, JsonSchema/IfKeyword.cs, JsonSchema/ItemsKeyword.cs, JsonSchema/JsonSchema.cs, JsonSchema/NotKeyword.cs, JsonSchema/OneOfKeyword.cs, JsonSchema/PatternPropertiesKeyword.cs, JsonSchema/PrefixItemsKeyword.cs, JsonSchema/PropertiesKeyword.cs, JsonSchema/PropertyNamesKeyword.cs, JsonSchema/ThenKeyword.cs, JsonSchema/UnevaluatedItemsKeyword.cs, JsonSchema/UnevaluatedPropertiesKeyword.cs, docs_source/usage/schema-keywords.md
=> deeply nested references

JsonSchema.Tests/OutputTests.cs, JsonSchema/AdditionalItemsKeyword.cs, JsonSchema/AdditionalPropertiesKeyword.cs, JsonSchema/ItemsKeyword.cs, JsonSchema/PatternPropertiesKeyword.cs, JsonSchema/PrefixItemsKeyword.cs, JsonSchema/PropertiesKeyword.cs, JsonSchema/RecursiveAnchorKeyword.cs, JsonSchema/UnevaluatedItemsKeyword.cs, JsonSchema/UnevaluatedPropertiesKeyword.cs, docs_source/usage/schema-datagen.md
Depends on https://github.com/json-schema-org/json-schema-spec/issues/1172
Relates to:
- #39 
- #89 
- #216 
- #221
=> adjust how annotations are used (discussion in JSON Schema spec for 2020-12 patch)

JsonSchema/JsonSchemaExtensions.cs
=> Add JsonSchemaExtensions

JsonSchema/JsonSchema.csproj, JsonSchema/JsonSchemaExtensions.cs, docs_source/release-notes/json-schema.md
Depends on #238 
Resolves #237
=> update version and release notes

.github/workflows/dotnet-core.yml, Json.More/Json.More.csproj, Json.More/JsonNodeEqualityComparer.cs, Json.More/JsonNodeExtensions.cs, JsonLogic/JsonLogic.csproj, JsonPatch/JsonPatch.csproj, JsonPath/JsonPath.csproj, JsonPointer.Tests/JsonPointerTests.cs, JsonPointer.Tests/RelativeJsonPointerTests.cs, JsonPointer/JsonPointer.cs, JsonPointer/JsonPointer.csproj, JsonPointer/RelativeJsonPointer.cs, JsonSchema.Data/JsonSchema.Data.csproj, JsonSchema.DataGeneration/JsonSchema.DataGeneration.csproj, JsonSchema.UniqueKeys/JsonSchema.UniqueKeys.csproj, JsonSchema/JsonSchema.csproj, json-everything.net/wwwroot/md/release-notes/json-logic.md, json-everything.net/wwwroot/md/release-notes/json-more.md, json-everything.net/wwwroot/md/release-notes/json-patch.md, json-everything.net/wwwroot/md/release-notes/json-path.md, json-everything.net/wwwroot/md/release-notes/json-pointer.md, json-everything.net/wwwroot/md/release-notes/json-schema-data.md, json-everything.net/wwwroot/md/release-notes/json-schema-datageneration.md, json-everything.net/wwwroot/md/release-notes/json-schema-generation.md, json-everything.net/wwwroot/md/release-notes/json-schema-unique-keys.md, json-everything.net/wwwroot/md/release-notes/json-schema.md
=> JsonNode support for Json.More and JsonPointer.Net

JsonSchema.Tests/FormatTests.cs, JsonSchema/AnyOfKeyword.cs, JsonSchema/Format.cs, JsonSchema/PredicateFormat.cs, JsonSchema/RegexFormat.cs, json-everything.net/wwwroot/md/release-notes/json-schema.md
=> Schema v2.2.1

JsonSchema.DataGeneration.Tests/ConditionalGenerationTests.cs, JsonSchema.DataGeneration.Tests/NotGenerationTests.cs, JsonSchema.DataGeneration.Tests/TestHelpers.cs, JsonSchema.DataGeneration/Generators/ObjectGenerator.cs, JsonSchema.DataGeneration/JsonSchema.DataGeneration.csproj, JsonSchema.DataGeneration/JsonSchemaExtensions.cs, JsonSchema.DataGeneration/Requirements/ItemsRequirementsGatherer.cs, JsonSchema.DataGeneration/Requirements/NumberRequirementsGatherer.cs, JsonSchema.DataGeneration/Requirements/PropertiesRequirementsGatherer.cs, JsonSchema.DataGeneration/Requirements/StringRequirementsGatherer.cs, JsonSchema.DataGeneration/RequirementsContext.cs, json-everything.net/wwwroot/md/release-notes/json-schema-datageneration.md
Resolves a conversation in JSON Schema slack.
=> Data generation and inferred types inside conditionals and inversions

JsonSchema.Generation.Tests/ClientTests.cs, JsonSchema.Tests/Suite/Suite.cs, json-everything.net/wwwroot/md/schema-generation.md, json-everything.net/wwwroot/md/schema-vocabs.md
=> Schemagen attributes mixup

JsonSchema.Tests/CreationTests.cs, JsonSchema/JsonSchema.cs, JsonSchema/JsonSchema.csproj, json-everything.net/wwwroot/md/release-notes/json-schema.md
=> add serializer options to schema creation methods

JsonPatch.Tests/PatchExtensionTests.cs, JsonPatch/PatchExtensions.cs
=> #283 Fix Bugs with PatchForArray

JsonSchema.Tests/DevTest.cs, JsonSchema.Tests/SelfValidationTest.cs, JsonSchema/ContentEncodingKeyword.cs, JsonSchema/JsonSchema.csproj, JsonSchema/MetaSchemas.Draft201909.cs, JsonSchema/MetaSchemas.Draft202012.cs, JsonSchema/MetaSchemas.Draft6.cs, JsonSchema/MetaSchemas.Draft7.cs, json-everything.net/wwwroot/md/release-notes/json-schema.md
🤦 self-validation tests weren't running
=> :facepalm: fixing issues with meta-schemas

JsonSchema.Generation/Generators/ObjectSchemaGenerator.cs, JsonSchema.Generation/JsonSchema.Generation.csproj, json-everything.net/Pages/Schema.razor, json-everything.net/wwwroot/md/release-notes/json-schema-generation.md
@ivarne when this is merged, the new version will be published.
Related to #296
=> Schemagen v3.0.2

JsonLogic.Tests/GithubTests.cs, JsonLogic/JsonLogic.csproj, JsonLogic/Rule.cs, json-everything.net/wwwroot/md/release-notes/json-logic.md
=> Issue313 deserializing null rules

JsonLogic.Tests/GithubTests.cs, JsonLogic/JsonNodeExtensions.cs
=> Fix 318: Numberify can parse floating point numbers in any culture

JsonSchema.Tests/Suite/Suite.cs, JsonSchema/PropertyDependenciesKeyword.cs, JsonSchema/PropertyDependency.cs
This still needs tests.  I'm probably going to add them to the test suite.  This PR will depend on one in that suite once created.
=> Schema - propertyDependencies

JsonSchema.Generation.Tests/ClientTests.cs, JsonSchema.Generation/JsonSchema.Generation.csproj, JsonSchema.Generation/NullableAttribute.cs, JsonSchema.Tests/Suite/Suite.cs, JsonSchema/Formats.cs, JsonSchema/JsonSchema.cs, json-everything.net/wwwroot/md/release-notes/json-schema-generation.md
=> Issue 325 schemagen nullable on multiple members

JsonSchema/DynamicRefKeyword.cs, JsonSchema/JsonSchema.cs, JsonSchema/JsonSchema.csproj, json-everything.net/wwwroot/md/release-notes/json-schema.md
Ref: [conversation in JSON Schema Slack](https://json-schema.slack.com/archives/C8CQ81GKF/p1662115715956779)
=> fix absolute schema location in output

JsonSchema.Generation/PropertyNamingMethods.cs
=> Update upper kebab case documentation comment.

JsonSchema.Tests/BuilderExtensions.cs, JsonSchema.Tests/FetchTests.cs, JsonSchema.Tests/VocabularyTests.cs, JsonSchema/JsonSchema.cs, JsonSchema/JsonSchema.csproj, JsonSchema/ValidationOptions.cs, json-everything.net/wwwroot/md/release-notes/json-schema.md, json-everything.net/wwwroot/md/schema-basics.md
=> add custom keyword without vocabs support for 2019-09 and later

JsonSchema/JsonSchema.csproj, JsonSchema/ValidationContext.cs, json-everything.net/wwwroot/md/release-notes/json-schema.md
Another point for @Julian and [Bowtie](https://bowtie-json-schema.github.io/bowtie/)!
=> collect annotations when unevaluated keywords are present

JsonSchema.Benchmark/Program.cs, JsonSchema.Tests/OutputTests.cs, JsonSchema.Tests/Suite/Output.cs, JsonSchema.Tests/Suite/TestCase.cs, JsonSchema.Tests/Suite/Validation.cs, JsonSchema.Tests/TestEnvironment.cs, JsonSchema/EvaluationResults.cs, JsonSchema/JsonSchema.csproj, JsonSchema/PropertyDependenciesKeyword.cs
Supports https://github.com/json-schema-org/JSON-Schema-Test-Suite/pull/619
=> added suite to run proposed output tests

Json.More.Tests/Json.More.Tests.csproj, JsonLogic.Tests/JsonLogic.Tests.csproj, JsonPatch.Tests/JsonPatch.Tests.csproj, JsonPath.Tests/JsonPath.Tests.csproj, JsonPath/Expressions/AddOperator.cs, JsonPath/Expressions/GreaterThanOperator.cs, JsonPath/Expressions/GreaterThanOrEqualToOperator.cs, JsonPath/Expressions/LessThanOperator.cs, JsonPath/Expressions/LessThanOrEqualToOperator.cs, JsonPath/Expressions/PathExpressionNode.cs, JsonPath/JsonPath.csproj, JsonPath/PathParser.cs, JsonPath/PathSegment.cs, JsonPointer.Tests/JsonPointer.Tests.csproj, JsonSchema.Data.Tests/JsonSchema.Data.Tests.csproj, JsonSchema.DataGeneration.Tests/JsonSchema.DataGeneration.Tests.csproj, JsonSchema.Generation.Tests/JsonSchema.Generation.Tests.csproj, JsonSchema.OpenApi.Tests/JsonSchema.OpenApi.Tests.csproj, JsonSchema.Tests/JsonSchema.Tests.csproj, JsonSchema.UniqueKeys.Tests/JsonSchema.UniqueKeys.Tests.csproj, Yaml2JsonNode.Tests/Yaml2JsonNode.Tests.csproj, json-everything.net/wwwroot/md/release-notes/json-path.md
I [added a bunch of tests](https://github.com/jsonpath-standard/jsonpath-compliance-test-suite/pull/11) to the JSON Path test suite and found a few bugs in filter expressions.  This fixes those bugs.
=> fixed some issues with expressions

JsonSchema.DataGeneration.Tests/GithubTests.cs, JsonSchema.DataGeneration/Generators/EnumGenerator.cs, JsonSchema.DataGeneration/JsonSchema.DataGeneration.csproj, json-everything.net/wwwroot/md/release-notes/json-schema-datageneration.md
=> enum datagen should copy the values from the schema, not use them directly

JsonSchema.Data/DataKeyword.cs, JsonSchema.Data/JsonSchema.Data.csproj, JsonSchema.Data/UriIdentifier.cs, json-everything.net/Pages/Schema.razor, json-everything.net/wwwroot/md/examples/schemadata/data-ref.md, json-everything.net/wwwroot/md/examples/schemadata/external-ref.md, json-everything.net/wwwroot/md/release-notes/json-schema-data.md
Resolves #391
Also provides a fix for the data keyword.
=> add examples for schema data usage; actually use external data registry

.github/workflows/dotnet-core.yml, Json.More.Tests/Json.More.Tests.csproj, JsonLogic.Tests/JsonLogic.Tests.csproj, JsonPatch.Tests/GithubTests.cs, JsonPatch.Tests/JsonPatch.Tests.csproj, JsonPath.Tests/JsonPath.Tests.csproj, JsonPointer.Tests/JsonPointer.Tests.csproj, JsonSchema.Data.Tests/JsonSchema.Data.Tests.csproj, JsonSchema.DataGeneration.Tests/JsonSchema.DataGeneration.Tests.csproj, JsonSchema.Generation.Tests/JsonSchema.Generation.Tests.csproj, JsonSchema.OpenApi.Tests/JsonSchema.OpenApi.Tests.csproj, JsonSchema.Tests/JsonSchema.Tests.csproj, JsonSchema.UniqueKeys.Tests/JsonSchema.UniqueKeys.Tests.csproj, Yaml2JsonNode.Tests/Yaml2JsonNode.Tests.csproj
Dropping JUnit logger because of https://github.com/spekt/junit.testlogger/issues/59
=> use trx test logger

JsonPatch.Tests/GithubTests.cs, JsonPatch/JsonPatch.csproj, JsonPatch/ReplaceOperationHandler.cs, json-everything.net/wwwroot/md/release-notes/json-patch.md
=> replicate issue

.github/workflows/dotnet-core.yml
Relates to https://github.com/EnricoMi/publish-unit-test-result-action/issues/414
=> update test suites; use test branch for results action

JsonLogic.Tests/Files/more-tests.json, JsonLogic/JsonLogic.csproj, JsonLogic/Rules/MissingRule.cs, json-everything.net/wwwroot/md/release-notes/json-logic.md
=> `missing` checks truthiness not presence

JsonSchema.Tests/BundlingTests.cs, JsonSchema.Tests/TestEnvironment.cs, JsonSchema/JsonSchema.csproj, JsonSchema/JsonSchemaExtensions.cs, json-everything.net/wwwroot/md/release-notes/json-schema.md, json-everything.net/wwwroot/md/schema-basics.md
=> added basic bundling support

JsonLogic/Rules/LessThanEqualRule.cs
Issue: https://github.com/gregsdennis/json-everything/issues/420
=> Small typo issue in LessThanEqualRule

JsonSchema.Tests/Files/Issue419_config.json, JsonSchema.Tests/Files/Issue419_level1.json, JsonSchema.Tests/Files/Issue419_level2.json, JsonSchema.Tests/Files/Issue419_root.json, JsonSchema.Tests/GithubTests.cs, JsonSchema/JsonSchema.csproj, JsonSchema/SchemaRegistry.cs, json-everything.net/wwwroot/md/release-notes/json-logic.md, json-everything.net/wwwroot/md/release-notes/json-schema.md
Resolves #419 
Resolves #415
Closes #414
=> registration with inferred uri should still initialize the schema

JsonSchema.Tests/Files/Issue426_data.json, JsonSchema.Tests/Files/Issue426_schema.json, JsonSchema.Tests/GithubTests.cs, JsonSchema/RefKeyword.cs
Fix file fragment refs and add a test 
Resolves https://github.com/gregsdennis/json-everything/issues/426
=> File fragment refs

JsonPath.Tests/Suite/ComplianceTestSuiteTests.cs, JsonPath/JsonPath.csproj, JsonPath/MatchFunction.cs, JsonPath/SearchFunction.cs, JsonPath/UtilityExtensions.cs, json-everything.net/wwwroot/md/json-path.md, json-everything.net/wwwroot/md/release-notes/json-path.md
Depends on https://github.com/jsonpath-standard/jsonpath-compliance-test-suite/pull/30
=> improved support for regex matching unicode

JsonSchema.Tests/GithubTests.cs, JsonSchema/JsonSchema.cs, JsonSchema/JsonSchema.csproj, json-everything.net/wwwroot/md/release-notes/json-schema.md
=> another unresolved `$ref`

JsonSchema.Tests/Files/Referencing/base_data.json, JsonSchema.Tests/Files/Referencing/base_data_hash_uri.json, JsonSchema.Tests/Files/Referencing/base_schema.json, JsonSchema.Tests/Files/Referencing/ref_schema.json, JsonSchema.Tests/Files/Referencing/schema_with_#_in_uri.json, JsonSchema.Tests/ReferenceTests.cs
This is just the tests from my previous PR #430
=> Tests for the # file uri problem

JsonSchema.Tests/DevTest.cs, JsonSchema.Tests/FormatTests.cs, JsonSchema/Formats.cs, JsonSchema/JsonSchema.csproj, json-everything.net/wwwroot/md/release-notes/json-schema.md
=> fix date-time format regex to support rfc3339

JsonPath.Tests/Suite/CburgmerFeatureValidationTests.cs, JsonPath.Tests/Suite/ComplianceTestSuiteTests.cs, JsonPath/Expressions/FunctionExpressionParser.cs, JsonPath/JsonPath.cs, JsonPath/JsonPath.csproj, JsonPath/LengthFunction.cs, JsonPath/PathParser.cs, JsonPath/PathParsingOptions.cs, JsonPath/UtilityExtensions.cs
Depends on https://github.com/jsonpath-standard/jsonpath-compliance-test-suite/pull/37
=> whitespace handling improvements

JsonPath.Tests/DevTest.cs, JsonPath.Tests/GithubTests.cs, JsonPath/Expressions/GreaterThanOperator.cs, JsonPath/Expressions/GreaterThanOrEqualToOperator.cs, JsonPath/Expressions/LessThanOperator.cs, JsonPath/Expressions/LessThanOrEqualToOperator.cs, JsonPath/JsonPath.csproj, tools/ApiDocsGenerator/release-notes/rn-json-path.md
=> Fix string comparisons in paths

JsonPath/Expressions/BooleanResultExpressionNode.cs, JsonPath/FilterSelector.cs, JsonPath/IFilterExpression.cs, JsonPath/IHaveShorthand.cs, JsonPath/ISelector.cs, JsonPath/IndexSelector.cs, JsonPath/JsonPath.cs, JsonPath/JsonPath.csproj, JsonPath/NameSelector.cs, JsonPath/SliceSelector.cs, JsonPath/WildcardSelector.cs, tools/ApiDocsGenerator/release-notes/rn-json-path.md
Resolves #465
@qt-kaneko, I think this is the level of exposure I'm comfortable with.  Let me know if this suits your needs.
=> exposing primary portions of model; makes exposed API more consistent

JsonSchema.Tests/BaseDocumentTests.cs, JsonSchema/JsonNodeBaseDocument.cs, JsonSchema/JsonSchema.csproj, tools/ApiDocsGenerator/release-notes/rn-json-schema.md
=> replicate issue with test

JsonSchema/Localization/Resources.nb-no.resx, JsonSchema/Localization/Resources.sv-se.resx
Resolves #457 Adding resources for Sweden and Norway
=> sweden and norway resources

Meta-Schemas/2020-12/validation.json, Yaml2JsonNode.Tests/ClientTests.cs, Yaml2JsonNode/Yaml2JsonNode.csproj, Yaml2JsonNode/YamlConverter.cs, tools/ApiDocsGenerator/release-notes/rn-yaml.md
=> yaml nulls aren't respected

JsonSchema.Generation.Tests/BoundaryTests.cs, JsonSchema.Generation.Tests/TypeAttributeTests.cs, JsonSchema.Generation/Attributes/ExclusiveMaximumAttribute.cs, JsonSchema.Generation/Attributes/ExclusiveMinimumAttribute.cs, JsonSchema.Generation/Attributes/IfMaxAttribute.cs, JsonSchema.Generation/Attributes/IfMinAttribute.cs, JsonSchema.Generation/Attributes/MaximumAttribute.cs, JsonSchema.Generation/Attributes/MinimumAttribute.cs, JsonSchema.Generation/JsonSchema.Generation.csproj, JsonSchema.Generation/TypeExtensions.cs, tools/ApiDocsGenerator/release-notes/rn-json-schema-generation.md
=> fix min/max attributes to clamp to decimal number range

JsonPath.Tests/GithubTests.cs, JsonPath/JsonPath.cs, JsonPath/JsonPath.csproj, tools/ApiDocsGenerator/release-notes/rn-json-path.md
=> Path - error when try-parsing empty string

Yaml2JsonNode/Yaml2JsonNode.csproj, Yaml2JsonNode/YamlConverter.cs, tools/ApiDocsGenerator/release-notes/rn-yaml.md
Mised conversion of null from JsonNode back into YamlNode.
=> fix null to yaml problem

CrossProjectTesting/CrossProjectTesting.csproj, CrossProjectTesting/ResultsExtensions.cs, CrossProjectTesting/UnitTest1.cs, CrossProjectTesting/Usings.cs, JsonSchema/JsonSchema.cs, JsonSchema/JsonSchema.csproj, JsonSchema/SchemaConstraint.cs, JsonSchema/nuspec/JsonSchema.Net.nuspec, json-everything.sln, tools/ApiDocsGenerator/release-notes/rn-json-schema.md
Related to https://github.com/dotnet/docfx/issues/9146
Resolves #502
=> fix parallel constraint generation

JsonPath.Tests/Suite/ComplianceTestSuiteTests.cs, JsonPath/JsonPath.csproj, JsonPath/PathParser.cs, tools/ApiDocsGenerator/release-notes/rn-json-path.md
=> Disparity between Parse and TryParse

JsonSchema.CodeGeneration/JsonSchema.CodeGeneration.csproj, JsonSchema.CodeGeneration/Model/ModelGenerator.cs, tools/ApiDocsGenerator/release-notes/rn-json-schema-codegeneration.md
=> support $schema/$id in base; expose validation results in exception

JsonSchema.Generation.Tests/PropertyNameResolverTests.cs, JsonSchema.Generation.Tests/PropertyNamingMethodTests.cs, JsonSchema.Generation/Generators/ObjectSchemaGenerator.cs, JsonSchema.Generation/JsonSchema.Generation.csproj, JsonSchema.Generation/PropertyNameResolvers.cs, JsonSchema.Generation/PropertyNamingMethods.cs, JsonSchema.Generation/SchemaGeneratorConfiguration.cs, tools/ApiDocsGenerator/release-notes/rn-json-schema-generation.md
=> Publish branch for #528

JsonPatch.Tests/GithubTests.cs, JsonSchema.Generation.Tests/ClientTests.cs, JsonSchema.Generation/AttributeHandler.cs, JsonSchema.Generation/JsonSchema.Generation.csproj, tools/ApiDocsGenerator/release-notes/rn-json-schema-generation.md
=> Some built-in attributes should be considered "handled"

JsonSchema.Tests/Serialization/DeserializationTests.cs, JsonSchema/JsonSchema.csproj, JsonSchema/Serialization/ValidatingJsonConverter.cs, tools/ApiDocsGenerator/release-notes/rn-json-schema.md
=> Stack overflow when serializing multiple times

JsonSchema.Generation.Tests/SchemaGenerationTests.cs, JsonSchema.Generation/Attributes/DefaultAttribute.cs, JsonSchema.Generation/Intents/DefaultIntent.cs, JsonSchema.Generation/Intents/ElseIntent.cs, JsonSchema.Generation/Intents/IfIntent.cs, JsonSchema.Generation/Intents/ThenIntent.cs, JsonSchema.Generation/JsonSchema.Generation.csproj, tools/ApiDocsGenerator/release-notes/rn-json-schema-generation.md
=> Default attribute for schema generation

JsonPointer/JsonPointer.csproj, JsonPointer/JsonPointerJsonConverter.cs, JsonPointer/RelativeJsonPointerJsonConverter.cs, tools/ApiDocsGenerator/release-notes/rn-json-pointer.md
=> update json converters to support source gen

JsonPointer.Tests/ExpressionCreationTests.cs, JsonPointer/JsonPointer.cs, JsonPointer/JsonPointer.csproj, tools/ApiDocsGenerator/release-notes/rn-json-pointer.md
=> support pointer creation using variables

JsonSchema.Data.Tests/Suite/Suite.cs, JsonSchema.Data.Tests/Tests.cs, JsonSchema.Data/JsonPathIdentifier.cs, JsonSchema.Data/JsonSchema.Data.csproj, JsonSchema.Data/JsonSchemaBuilderExtensions.cs, JsonSchema.Data/MetaSchemas.cs, JsonSchema.Data/Vocabularies.cs, json-everything.net/json-everything.net.csproj, json-everything.net/wwwroot/meta/data-2023, json-everything.net/wwwroot/meta/vocab/data-2023, tools/ApiDocsGenerator/release-notes/rn-json-schema-data.md
Depends on https://github.com/gregsdennis/json-everything/pull/577
(doesn't really depend on it, but it has some other things that should ideally be merged first.)
=> update for data-2023 and add path tests

JsonSchema.Generation.Tests/NullabilityTests.cs, JsonSchema.Generation.Tests/PropertyOrderTests.cs, JsonSchema.Generation/GeneralExtensions.cs, JsonSchema.Generation/Generators/NullableValueTypeSchemaGenerator.cs, JsonSchema.Generation/JsonSchema.Generation.csproj, JsonSchema.Generation/MemberInfoMetadataComparer.cs, JsonSchema.Generation/Refiners/NullabilityRefiner.cs, JsonSchema.Generation/TypeExtensions.cs, tools/ApiDocsGenerator/release-notes/rn-json-schema-generation.md
=> Handle nullable value types better

JsonPath.Tests/DeferredExecutionTests.cs, JsonPath/GeneralExtensions.cs, JsonPath/JsonPath.csproj, JsonPath/NodeList.cs
=> add deferred execution tests

JsonSchema.Tests/Serialization/DeserializationTests.cs, JsonSchema/Serialization/ValidatingJsonConverter.cs, json-everything.sln.DotSettings
=> support inaccessible types

Json.More.Tests/JsonArrayTupleConverterDeserializationTests.cs, Json.More.Tests/JsonArrayTupleConverterSerializationTests.cs, Json.More/Json.More.csproj, Json.More/JsonArrayTupleConverter.cs, Json.More/JsonCollectionTupleConverter.cs, tools/ApiDocsGenerator/release-notes/rn-json-more.md
Related to https://github.com/dotnet/runtime/issues/70352#issuecomment-1895750363
See a need, fill a need.
=> add tuple array conversion

JsonE/Expressions/Functions/SplitFunction.cs, JsonE/Expressions/IndexSegment.cs, JsonE/Expressions/SliceSegment.cs, JsonE/JsonE.csproj, JsonE/Operators/LetOperator.cs, tools/ApiDocsGenerator/release-notes/rn-json-e.md
JSON-e pushed some new tests that need coverage.
Updated other test suites as well, but they pass.
=> update string ops to use text elements not chars

JsonPath/IPathFunctionDefinition.cs, JsonPath/JsonPath.csproj, JsonPath/JsonPathConverter.cs
Updates JsonPath.Net for NativeAOT support
=> update jsonpath for native aot

Json.More/TypeResolverOptionsManager.cs, JsonSchema/ContainsKeyword.cs, JsonSchema/ContentSchemaKeyword.cs, JsonSchema/ErrorMessages.cs, JsonSchema/JsonNodeBaseDocument.cs, JsonSchema/JsonSchema.cs, JsonSchema/JsonSchemaSerializerContext.cs, JsonSchema/SchemaKeywordRegistry.cs
This should allow us to use all of those options tricks in the other libs.  (It'll let others use it too!)
=> Native aot context options mgr

JsonSchema/Localization/Resources.ru.resx
Hello! 👋
I added translation for Russian language and did small fix for default English translation.
=> Add translation for Russian language and small fix in default English translation

JsonSchema.Tests/EvaluationOptionsTests.cs, JsonSchema/EvaluationOptions.cs, JsonSchema/JsonSchema.cs, JsonSchema/JsonSchema.csproj, JsonSchema/PatternPropertiesKeyword.cs, JsonSchema/SchemaRegistry.cs, tools/ApiDocsGenerator/release-notes/rn-json-schema.md
@danielstarck I think this should resolve the issues that were highlighted by #608.
=> Reusing schemas with different/changed options

JsonSchema.DataGeneration.Tests/NumberGenerationTests.cs, JsonSchema.DataGeneration.Tests/RefTests.cs, JsonSchema.DataGeneration.Tests/TestHelpers.cs, JsonSchema.DataGeneration/IRequirementsGatherer.cs, JsonSchema.DataGeneration/JsonSchema.DataGeneration.csproj, JsonSchema.DataGeneration/JsonSchemaExtensions.cs, JsonSchema.DataGeneration/NumberRangeSet.cs, JsonSchema.DataGeneration/Requirements/AllOfRequirementsGatherer.cs, JsonSchema.DataGeneration/Requirements/AnyOfRequirementsGatherer.cs, JsonSchema.DataGeneration/Requirements/ConditionalRequirementsGatherer.cs, JsonSchema.DataGeneration/Requirements/ConstRequirementsGatherer.cs, JsonSchema.DataGeneration/Requirements/ContainsRequirementsGatherer.cs, JsonSchema.DataGeneration/Requirements/EnumRequirementsGatherer.cs, JsonSchema.DataGeneration/Requirements/FalseRequirementsGatherer.cs, JsonSchema.DataGeneration/Requirements/ItemsRequirementsGatherer.cs, JsonSchema.DataGeneration/Requirements/NotRequirementsGatherer.cs, JsonSchema.DataGeneration/Requirements/NumberRequirementsGatherer.cs, JsonSchema.DataGeneration/Requirements/OneOfRequirementsGatherer.cs, JsonSchema.DataGeneration/Requirements/PropertiesRequirementsGatherer.cs, JsonSchema.DataGeneration/Requirements/RefRequirementsGatherer.cs, JsonSchema.DataGeneration/Requirements/StringRequirementsGatherer.cs, JsonSchema.DataGeneration/Requirements/TypeRequirementsGatherer.cs, tools/ApiDocsGenerator/release-notes/rn-json-schema-datageneration.md
=> Add support for pointer refs

Json.More/Json.More.csproj, Json.More/JsonNodeExtensions.cs, JsonSchema.Tests/GithubTests.cs, tools/ApiDocsGenerator/release-notes/rn-json-more.md
=> UInt support in .GetInteger()

JsonSchema/Localization/Resources.pl-PL.resx, JsonSchema/nuspec/JsonSchema.Net.pl-PL.nuspec, README.md
=> add polish translations

JsonSchema/Localization/Resources.it.resx, JsonSchema/nuspec/JsonSchema.Net.it.nuspec, README.md
Add resource and nuspec for Italian localization and update README.
=> Add Italian localization

JsonSchema.Tests/GithubTests.cs, JsonSchema/JsonSchema.csproj, JsonSchema/JsonSerializerOptionsExtensions.cs, JsonSchema/SchemaKeywordRegistry.cs, tools/ApiDocsGenerator/release-notes/rn-json-schema.md
=> replicate problem with unit test

JsonE/JsonE.csproj, JsonE/Operators/FindOperator.cs, JsonE/Operators/OperatorRepository.cs, JsonLogic/JsonLogic.csproj, tools/ApiDocsGenerator/release-notes/rn-json-e.md, tools/ApiDocsGenerator/release-notes/rn-json-logic.md
Relates to https://github.com/json-e/json-e/pull/526
=> add `$find` operator

Json.More/JsonSerializerOptionsExtensions.cs, JsonSchema.Tests/AnchorTests.cs, JsonSchema.Tests/ResultsExtensions.cs, JsonSchema.Tests/Suite/Output.cs, JsonSchema/AnchorKeyword.cs, JsonSchema/DynamicAnchorKeyword.cs, JsonSchema/DynamicRefKeyword.cs, JsonSchema/JsonSchema.cs, JsonSchema/JsonSchema.csproj, JsonSchema/MetaSchemas.Draft201909.cs, JsonSchema/MetaSchemas.Draft202012.cs, JsonSchema/RecursiveRefKeyword.cs, JsonSchema/RefKeyword.cs, tools/ApiDocsGenerator/release-notes/rn-json-schema.md
Depends on https://github.com/json-schema-org/JSON-Schema-Test-Suite/pull/724
Resolves #690
=> update 2020-12 anchor verification

JsonSchema/JsonSchemaExtensions.KeywordAccess.cs
Keywords that are list based might benefit for their extensions to also be list based.
=> IReadOnlyCollections to IReadOnlyLists in KeywordAccess extensions

src/JsonPath/Expressions/BinaryLogicalExpressionNode.cs, src/JsonPath/Expressions/BooleanResultExpressionNode.cs, src/JsonPath/Expressions/ExpressionParser.cs, src/JsonPath/Expressions/FunctionBooleanExpressionNode.cs, src/JsonPath/Expressions/FunctionExpressionParser.cs, src/JsonPath/Expressions/ILogicalExpressionParser.cs, src/JsonPath/Expressions/LogicalExpressionNode.cs, src/JsonPath/Expressions/UnaryLogicalExpressionNode.cs, src/JsonPath/JsonPath.csproj, tools/ApiDocsGenerator/release-notes/rn-json-path.md
Depends on https://github.com/jsonpath-standard/jsonpath-compliance-test-suite/pull/83
Discovered these tests while writing lessons for https://learn.json-everything.net/json-path.
=> fix order of operation for boolean ops in path expressions

src/JsonSchema/SchemaRegistry.cs
In order to support Graeae, a backdoor needs to be created to allow for registration of new spec versions.  This is only to be used if you know what you're doing.
Relates to https://github.com/gregsdennis/Graeae/issues/5
=> added backdoor for new schema spec versions

json-everything.net/Models/SponsorData.cs, json-everything.net/Services/DataManager.cs, json-everything.net/Shared/Feature.razor, json-everything.net/Shared/SponsorBubble.razor, src/Json.More/Json.More.csproj, src/JsonLogic.Tests/GithubTests.cs, src/JsonLogic/JsonLogic.cs, src/JsonLogic/JsonLogic.csproj, src/JsonSchema.Data/JsonPathIdentifier.cs, src/JsonSchema.Tests/GithubTests.cs, src/Yaml2JsonNode/Yaml2JsonNode.csproj, tools/ApiDocsGenerator/release-notes/rn-json-logic.md
JSON Logic nested variable support
Resolves #807
=> JSON Logic nested variable support

src/JsonPath/Expressions/FunctionExpressionParser.cs
Motivation:
Clean code for easy understand
=> chore: clean up when parsing node list argument

src/JsonSchema/Localization/Resources.de.resx, src/JsonSchema/nuspec/JsonSchema.Net.de.nuspec, src/JsonSchema/nuspec/README.de.md
This PR adds a German translation of JsonSchema.Net to make it easier for German speakers to understand error messages.
None.
=> Add German Localization

src/JsonPath.Tests/ExpressionTests.cs, src/JsonPath/Expressions/FunctionValueExpressionNode.cs
Resolves https://github.com/json-everything/json-everything/issues/836
=> chore: Add nested noop test case

src/JsonSchema/nuspec/JsonSchema.Net.de.nuspec, src/JsonSchema/nuspec/JsonSchema.Net.pl-PL.nuspec
I saw the failing GitHub Actions and that I made a mistake in the nuspec file in my last PR for the German language. I also set what I think is the correct language in the `pl-PL` nuspec file.
=> Fix language nuspec files

.github/workflows/dotnet-core.yml
Just updating the build with some better test results.  Borrowed from a build at work.
=> add test reporter

.github/workflows/publish-schema-sign.yml
Just testing package signing.  Move along.
=> add action to test signing a package

.github/workflows/publish-schema-sign.yml, src/JsonPointer/JsonPointer.cs, src/JsonPointer/JsonPointer.csproj, src/JsonPointer/PointerSegment.cs, src/JsonPointer/RelativeJsonPointer.cs, src/JsonPointer/UtilityExtensions.cs, src/JsonSchema.Generation/XmlComments/DocXmlReader.cs, src/JsonSchema.Tests/DependencyChecks.cs, src/JsonSchema.Tests/FormatTests.cs, src/JsonSchema/Formats.cs, src/JsonSchema/JsonSchema.csproj, src/JsonSchema/nuspec/JsonSchema.Net.nuspec, tools/ApiDocsGenerator/release-notes/rn-json-pointer.md, tools/ApiDocsGenerator/release-notes/rn-json-schema-generation.md, tools/ApiDocsGenerator/release-notes/rn-json-schema.md
- Updates `hostname` and `idn-hostname` formats for JsonSchema.Net
- Updates JsonSchema.Net nuget package to include libs for .Net 9
- Further reduces allocations in JsonPointer.Net
Resolves #852
Resolves #863
Resolves #867 
Depends on #864
=> Multi release
